use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Kalanhall/Specs.git'
inhibit_all_warnings!

target 'LoginService_Example' do
  pod 'LoginService', :path => '../'
  pod 'LoginServiceInterface', :path=>'/Users/kalan/Desktop/Swift/LoginServiceInterface'

  target 'LoginService_Tests' do
    inherit! :search_paths

    
  end
end
